### ISSUE TITLE
is it possible to let the figure interactive

### ISSUE THREAD

**Issue by GuangchuangYu** [timelyportfolio/svgPanZoom#4]
Thank you for developing such a great package.

I am wonder is it possible to make the figure interactive like figures generated by ggvis.

Best wishes,
Guangchuang

**Comment by timelyportfolio** [comment]
I would love to do this, but it is unfortunately beyond the scope of this `htmlwidget`, since the primary purpose is general and broad zoom to nearly all R graphics.  To enhance with interactivity would require separate methods for each type of output.  If you want to add interactivity to a single graph, I'd be happy to work with you on an `htmlwidget` targeting this.

**Comment by timelyportfolio** [comment]
by the way thanks for your work on `ggtree`

**Comment by GuangchuangYu** [comment]
Thank you for your reply and many good htmlwidget packages.

New version of shiny already bring this feature to R community (see http://www.r-bloggers.com/shiny-0-12-interactive-plots-with-ggplot2/). It may not work with svg currently, but it's enough for me.
